### ISSUE TITLE
ci: Cancel superseded jobs

### ISSUE THREAD

**Issue by duesee** [dequbed/rsasl#37]
Jobs that are superseded by another CI run should be canceled. See https://github.com/duesee/imap-codec/issues/92

TLDR;

We could add ...

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```

... to all workflow files to eagerly cancel jobs that won't matter in the future.

I could make a PR if you like this change :-)
